runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /asknow/.*
  script: asknow.app

- url: /css
  static_dir: css

- url: /images
  static_dir: images

libraries:
- name: jinja2
  version: latest
